headers for task 4
kirillova-ak5/poly-cpp pull request #2
Opened 2020-06-16 22:40 UTC by kirillova-ak5

2020-06-17 08:34 UTC, Gandy123 commented on lab004/Image.h
> +  image() : W(0), H(0), Pixels(NULL)
Уровни доступа расставьте и переименуйте struct в класс. Погуглите разницу в кратце struct в С++ используют в основном для POD типов

2020-06-17 08:35 UTC, Gandy123 commented on lab004/Image.h
> +  {
большие по размеру методы больше одной строки обычно выносят в cpp файл не держат в h-нике

2020-06-17 08:35 UTC, Gandy123 commented on lab004/Image.h
> +  BOOL LoadBMP(CHAR* FileName)
char замените на std::string или std::string_view

2020-06-17 08:36 UTC, Gandy123 commented on lab004/Image.h
> +  UINT W, H;
std::vector

2020-06-17 08:37 UTC, Gandy123 commented on lab004/levels.h
> +  virtual VOID Draw(VOID) = 0;
члены класса не надо public делать лучше код который с ними работать переносить в класс

2020-06-17 08:38 UTC, Gandy123 commented on lab004/levels.h
> +};
зачем здесь enum ? он не используется в самой структуре и городить структуру только для того чтобы сделать в ней поинтер и enum это странное решение

2020-06-17 08:39 UTC, Gandy123 commented on lab004/levels.h
> +   texture Background;
тоже что и выше, все переменные убрать в private или protected, при этом не писать к ним getter-ы а попробовать код, который с ними работает вынести внутрь класса

2020-06-17 08:39 UTC, Gandy123 requested changes
.

2020-06-17 13:30 UTC, kirillova-ak5 commented on lab004/levels.h
> +};
для того чтобы определять что хранится в данной точке при респонсе, мне такой вариант показался наиболее удобным

2020-06-18 13:11 UTC, Gandy123 commented on lab004/levels.cpp
> +    {
вот это перепишите на полиморфный вариант, чтобы убрать switch

2020-06-19 03:08 UTC, merged